config/routes.rb
Rails.application.routes.draw do
  root 				'up_arise#Home'
  get 'about'	=>	'up_arise#About'
  get 'members'	=>	'up_arise#Members'
  get 'events'	=>	'up_arise#Events'
  get 'contact'	=>	'up_arise#Contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
  	render text: "Hello World!"
  end
end

app/controllers/up_arise_controller.rb
class UpAriseController < ApplicationController
  def Home
  end

  def About
  end

  def Members
  end

  def Events
  end

  def Contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/up_arise_helper.rb
module UpAriseHelper
	def full_title(page_title)
		base_title = "UP ARISE"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	The UP ARISE Website is brought to you by:
	JARDELEZA, Agnes
	ITURRALDE, Elaine
	ASIDDAO, Mark
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
	<div class = "container">
		<%= link_to "UP ARISE", root_path, id: "logo" %>
		<nav>
			<ul class = "nav navbar-nav navbar-right">
			<li><%= link_to "Home", 	root_path %></li>
			<li><%= link_to "About", 	about_path %></li>
			<li><%= link_to "Members", 	members_path %></li>
			<li><%= link_to "Events", 	events_path %></li>
			<li><%= link_to "Contact", 	contact_path %></li>
			</ul>
		</nav>
	</div>
</header>
	

app/views/layouts/_shim.html.erb
<!==[if 1t IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/up_arise/About.html.erb
<% provide(:title, "About") %>
<h1>ABOUT</h1>
<p>About section.</p>

app/views/up_arise/Contact.html.erb
<% provide(:title, "Contact") %>
<h1>CONTACT</h1>
<p>Contact Section</p>

app/views/up_arise/Events.html.erb
<% provide(:title, "Events") %>
<h1>EVENTS</h1>
<p>Event Section</p>

app/views/up_arise/Home.html.erb
<% provide(:title, "Home") %>
<h1>HOME</h1>
<p>Home Section</p>

app/views/up_arise/Members.html.erb
<% provide(:title, "Members") %>
<h1>MEMBERS</h1>
<p>Members Section</p>